services:
  postgres:
    image: postgres:latest
    container_name: ylj-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ylj_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
